[2024-04-16T02:32:21.308+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: files_ext.extract_files scheduled__2024-04-15T00:00:00+00:00 [queued]>
[2024-04-16T02:32:21.316+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: files_ext.extract_files scheduled__2024-04-15T00:00:00+00:00 [queued]>
[2024-04-16T02:32:21.316+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 4
[2024-04-16T02:32:21.328+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): extract_files> on 2024-04-15 00:00:00+00:00
[2024-04-16T02:32:21.334+0000] {standard_task_runner.py:60} INFO - Started process 449 to run task
[2024-04-16T02:32:21.336+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'files_ext', 'extract_files', 'scheduled__2024-04-15T00:00:00+00:00', '--job-id', '1924', '--raw', '--subdir', 'DAGS_FOLDER/files_extraction.py', '--cfg-path', '/tmp/tmppqrkebc5']
[2024-04-16T02:32:21.338+0000] {standard_task_runner.py:88} INFO - Job 1924: Subtask extract_files
[2024-04-16T02:32:21.372+0000] {task_command.py:423} INFO - Running <TaskInstance: files_ext.extract_files scheduled__2024-04-15T00:00:00+00:00 [running]> on host fdd3cfdf3f53
[2024-04-16T02:32:21.434+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='files_ext' AIRFLOW_CTX_TASK_ID='extract_files' AIRFLOW_CTX_EXECUTION_DATE='2024-04-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-15T00:00:00+00:00'
[2024-04-16T02:32:21.436+0000] {s3.py:1393} INFO - Downloading source S3 file from Bucket vehicle with path orders/tolldata.tgz
[2024-04-16T02:32:21.443+0000] {base.py:83} INFO - Using connection ID 'minin_s3' for task execution.
[2024-04-16T02:32:21.444+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='minin_s3', conn_type='aws') credentials retrieved from login and password.
[2024-04-16T02:32:21.444+0000] {warnings.py:109} WARNING - <string>:9: AirflowProviderDeprecationWarning: extra['host'] is deprecated and will be removed in a future release. Please set extra['endpoint_url'] instead

[2024-04-16T02:32:21.591+0000] {logging_mixin.py:188} INFO - Error: An unexpected error occurred: [Errno 21] Is a directory: 'dags/'
[2024-04-16T02:32:21.592+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-16T02:32:21.600+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=files_ext, task_id=extract_files, execution_date=20240415T000000, start_date=20240416T023221, end_date=20240416T023221
[2024-04-16T02:32:21.629+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-16T02:32:21.643+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
