[2024-04-17T16:05:26.337+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_data.extract_process_started scheduled__2024-04-16T00:00:00+00:00 [queued]>
[2024-04-17T16:05:26.358+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_data.extract_process_started scheduled__2024-04-16T00:00:00+00:00 [queued]>
[2024-04-17T16:05:26.360+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 4
[2024-04-17T16:05:26.385+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): extract_process_started> on 2024-04-16 00:00:00+00:00
[2024-04-17T16:05:26.396+0000] {standard_task_runner.py:60} INFO - Started process 69 to run task
[2024-04-17T16:05:26.412+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_data', 'extract_process_started', 'scheduled__2024-04-16T00:00:00+00:00', '--job-id', '2032', '--raw', '--subdir', 'DAGS_FOLDER/etl_data.py', '--cfg-path', '/tmp/tmpp_6b94og']
[2024-04-17T16:05:26.440+0000] {standard_task_runner.py:88} INFO - Job 2032: Subtask extract_process_started
[2024-04-17T16:05:26.650+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_data.extract_process_started scheduled__2024-04-16T00:00:00+00:00 [running]> on host fdd3cfdf3f53
[2024-04-17T16:05:26.783+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_data' AIRFLOW_CTX_TASK_ID='extract_process_started' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-16T00:00:00+00:00'
[2024-04-17T16:05:26.785+0000] {python.py:202} INFO - Done. Returned value was: /opt/***
[2024-04-17T16:05:26.822+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=etl_data, task_id=extract_process_started, execution_date=20240416T000000, start_date=20240417T160526, end_date=20240417T160526
[2024-04-17T16:05:26.887+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-17T16:05:26.919+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
