[2024-04-15T09:06:09.116+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_data.extract_data_from_tsv scheduled__2024-04-13T00:00:00+00:00 [queued]>
[2024-04-15T09:06:09.149+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_data.extract_data_from_tsv scheduled__2024-04-13T00:00:00+00:00 [queued]>
[2024-04-15T09:06:09.150+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 4
[2024-04-15T09:06:09.199+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): extract_data_from_tsv> on 2024-04-13 00:00:00+00:00
[2024-04-15T09:06:09.215+0000] {standard_task_runner.py:60} INFO - Started process 339 to run task
[2024-04-15T09:06:09.220+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_data', 'extract_data_from_tsv', 'scheduled__2024-04-13T00:00:00+00:00', '--job-id', '1404', '--raw', '--subdir', 'DAGS_FOLDER/etl_data.py', '--cfg-path', '/tmp/tmpw9iy4r16']
[2024-04-15T09:06:09.225+0000] {standard_task_runner.py:88} INFO - Job 1404: Subtask extract_data_from_tsv
[2024-04-15T09:06:09.318+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_data.extract_data_from_tsv scheduled__2024-04-13T00:00:00+00:00 [running]> on host 41da1b14e620
[2024-04-15T09:06:09.447+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_data' AIRFLOW_CTX_TASK_ID='extract_data_from_tsv' AIRFLOW_CTX_EXECUTION_DATE='2024-04-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-13T00:00:00+00:00'
[2024-04-15T09:06:09.451+0000] {logging_mixin.py:188} INFO - Folder ../data/tolldata does not exist.
[2024-04-15T09:06:09.452+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-15T09:06:09.469+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=etl_data, task_id=extract_data_from_tsv, execution_date=20240413T000000, start_date=20240415T090609, end_date=20240415T090609
[2024-04-15T09:06:09.513+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-15T09:06:09.598+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
